### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Parameter specified as non-null is null: method com.zoontek.rnpermissions.RNPermissionsModule.requestNotifications, parameter options

### ISSUE THREAD

**Issue by nicolasdevienne** [zoontek/react-native-permissions#920]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

Fatal Exception: java.lang.NullPointerException: Parameter specified as non-null is null: method com.zoontek.rnpermissions.RNPermissionsModule.requestNotifications, parameter options
       at com.zoontek.rnpermissions.RNPermissionsModule.requestNotifications(:2)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:146)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:235)
       at java.lang.Thread.run(Thread.java:1012)

### Library version

5.2.0

### Environment info

```shell
"react": "18.3.1"
"react-native": "0.75.3"
"react-native-permissions": "5.2.0"
```

### Steps to reproduce

No Steps to reproduce

### Reproducible sample code

No Reproductible sample code

**Comment by zoontek** [comment]
@nicolasdevienne Please provide some context.

**Comment by nicolasdevienne** [comment]
@zoontek I think the issue is due to when Android version < 13 for some devices. Should we check the Android version before call the function requestNotifications ?

**Comment by zoontek** [comment]
I was thinking about the device, if you are running new architecture or not, how the code is called, etc.

**Comment by nicolasdevienne** [comment]
No I'm not running the new architecture dans the code is very simple :

```
        const { status } = await requestNotifications();
        if (!(status == RESULTS.GRANTED)) {
          ...
        }
```

Maybe add try/catch ?

**Comment by zoontek** [comment]
Given that you gave no reproduction info, I guess that you cannot reproduce it and maybe it occurred once and was reported by your bug tracker…

In that case yes, just handle the error case.

**Comment by nicolasdevienne** [comment]
I cannot reproduce because the issue is given by Firebase Crashlytics for several users since I published last week the new release of my app with the new version of your SDK :
- Android 9/Huawei P20 Lite
- Android 10/Huawei P30
- Android 12/Xiaomi Redmi Note 10 Pro
- Android 12/Oppo Reno4 Pro 5G

**Comment by zoontek** [comment]
> I cannot reproduce because the issue is given by Firebase Crashlytics for several users since I published last week the new release of my app with the new version of your SDK

What do you mean by "the new version of your SDK"? You did an update? From which version? Did it worked before?

Note that that's precisely why I asked for context before, all those infos [could have been in your initial message](https://dev.to/opensauced/how-to-write-a-good-issue-tips-for-effective-communication-in-open-source-5443).

**Comment by nicolasdevienne** [comment]
Sorry for the lack of details, I will try to be more specific. I was using SDK version 4.1.5 until now and last month I updated to 5.2.0 but I realized that the await request(PERMISSIONS.ANDROID.POST_NOTIFICATIONS) function was no longer working so I migrated to the await requestNotifications() function which seemed to work better except that if you call this function on devices running an Android version lower than 13 (SDK = 33) then it crashes the app. Adding a try/catch doesn't change anything. I think you just have to check the Android version before calling the function.

**Comment by zoontek** [comment]
Thanks for the infos. I finally got it, and it was dead-simple (and even in the error message).
According to [the documentation](https://github.com/zoontek/react-native-permissions?tab=readme-ov-file#requestnotifications), `requestNotifications` takes a required argument, `options`:

```ts
function requestNotifications(
  options: NotificationOption[], // <- even if only used by iOS, required
  rationale?: Rationale, // <- when arguments are not required, they are written with "?:"
): Promise<NotificationsResponse>;
```

So using this will work:

```ts
import {requestNotifications} from 'react-native-permissions';

// Just pass an empty array if your app is Android only
requestNotifications([]).then(({status, settings}) => {
  // …
});
```

**Comment by nicolasdevienne** [comment]
Arf yes it works! So "options" is only used by iOS but required and equals to [] for Android when API level is lower than 33. Thank you for the solution!

**Comment by zoontek** [comment]
@nicolasdevienne It's a non-issue with TypeScript, but not everyone is using it. I published a patch to make the argument optional: [v5.2.3](https://github.com/zoontek/react-native-permissions/releases/tag/5.2.3)

**Comment by ncoen97** [comment]
For the record I was using `request(PERMISSIONS.ANDROID.POST_NOTIFICATIONS);`.

The fix is to switch to `requestNotifications([]);`

Thanks guys.

**Comment by JeanSilvany** [comment]
The problem persists for me after disabling the new Arch.

![Image](https://github.com/user-attachments/assets/1c326ac6-8480-4ebe-acdc-d6a6ba0f10dc)

**Comment by Serck96** [comment]
@JeanSilvany I found the same problem today. The error appears when you use a specific permission for iOS or another platform on Android.

**Comment by Brma1048** [comment]
@Serck96 I faced the same problem today after upgrading to v5.
@zoontek Do we need to check the platform before requesting permissions? Previously, I requested permissions using await request(PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY); for both iOS and Android. Now, I need to check if I'm on iOS and only request the permission in that case.
